#!/usr/bin/env python3
"""Generate the just-the-docs site in docs/ from README.md and reference/.

README.md is the single source of truth. Each numbered `## N. Title` section of
the README becomes one page of the site, so the guide on GitHub and the guide on
GitHub Pages can never drift. CI runs this with --check and fails if they have.

What the transform does to each README section:

  * the `## N. Title` heading becomes the page's single H1 (the page title), and
    every deeper heading moves up one level - so `### 5.1 Charge request`
    becomes `## 5.1 Charge request`, keeping its text and therefore its anchor;
  * image paths (`docs/assets/...`) become `{{ '/assets/...' | relative_url }}`;
  * in-README anchors (`#51-charge-request`) become links to the page that now
    holds that heading (`../api-reference/#51-charge-request`);
  * links to reference/*.md become links to their generated pages, and links to
    repository files (LICENSE, NOTICE) become absolute GitHub URLs.

The three reference files are published verbatim under /reference/, with only
their H1 restated and their image paths rewritten.

Each page keeps its `last_modified_at` while its content is unchanged and only
moves when the content does, so --check is stable. jekyll-sitemap publishes it
as <lastmod> and the structured data as dateModified.

    python3 tools/build_docs.py          # regenerate
    python3 tools/build_docs.py --check  # exit 1 if docs/ is stale (used by CI)
"""

import argparse
import datetime
import io
import os
import posixpath
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
README = os.path.join(ROOT, "README.md")
REPO = "https://github.com/67even/ecocash-instant-payment-api"
SITE_NAME = "EcoCash EIP Developer Guide"

BANNER = "# GENERATED by tools/build_docs.py from README.md / reference/ - edit the source, then re-run it."
DATE_TOKEN = "@@LAST_MODIFIED@@"
PUBLISHED = "2026-09-21"

# README section number -> (output file, permalink, nav title, nav_order, meta description)
# Titles are short because just-the-docs uses `title` for the sidebar label AND the
# <title> tag; the descriptions carry the search phrases and fill the SERP snippet.
SECTIONS = {
    1: ("index.md", "/", "Home", 1,
        "Integrate the EcoCash Instant Payment (EIP) API: sandbox access, Basic auth, "
        "charge, lookup and refund, with PHP, Node.js, Python, Java and C# examples."),
    2: ("getting-started.md", "/getting-started/", "Get sandbox access", 3,
        "Get EcoCash EIP sandbox access step by step: register, request credentials, "
        "find them in the portal inbox, activate them and verify a test number."),
    3: ("authentication.md", "/authentication/", "Authentication", 4,
        "How EcoCash EIP API authentication works: HTTP Basic auth header, storing "
        "sandbox credentials and merchant values safely, and fixing 401 and 403 errors."),
    4: ("first-payment.md", "/first-payment/", "Your first payment", 5,
        "Make your first EcoCash sandbox payment with cURL: charge a wallet, approve the "
        "USSD PIN prompt, look up the status and refund it, in four steps."),
    5: ("api-reference.md", "/api-reference/", "API reference", 6,
        "EcoCash EIP API reference: charge request, transaction lookup and refund "
        "endpoints with every field, request body, response and HTTP status code."),
    6: ("errors.md", "/errors/", "Statuses & errors", 7,
        "EcoCash EIP transaction statuses and error codes E001 to E015: what each means, "
        "how to fix it, which to retry, and rules that prevent double charges."),
    7: ("testing.md", "/testing/", "Sandbox testing", 8,
        "Test EcoCash payments in the sandbox: PIN test matrix, whitelisted test numbers, "
        "sandbox merchant values, SMS notifications and the TC-001 to TC-006 checklist."),
    8: ("sdks.md", "/sdks/", "SDKs & code examples", 9,
        "EcoCash EIP API code examples in PHP/Laravel, Node.js, Python, Java Spring and "
        "C# .NET, plus the pitfalls in the portal's official SDK samples."),
    9: ("go-live.md", "/go-live/", "Going live", 10,
        "Go live with EcoCash Instant Payment: merchant line validation, test evidence, "
        "the completed test script, the production request and a go-live checklist."),
    10: ("troubleshooting.md", "/troubleshooting/", "Troubleshooting", 11,
         "Fix EcoCash EIP API problems fast: 401, 404 and 400 errors, payments stuck on "
         "PENDING, refund failures, missing SMS and test number OTP issues."),
    11: ("known-issues.md", "/known-issues/", "Known portal issues", 12,
         "Where the EcoCash developer portal contradicts itself: amount format, refund "
         "tranType, merchant values and status field names, and what to do about each."),
    12: ("install.md", "/install/", "Installing the skill", 2,
         "Install the EcoCash Instant Payment Claude skill in Claude Code or claude.ai: "
         "what it does, example prompts, the eip_cli.py linter and its benchmark results."),
    13: ("about.md", "/about/", "About this guide", 14,
         "About this independent EcoCash EIP developer guide: repository layout, how the "
         "site is generated, sources, licence and non-affiliation disclaimer."),
}

# reference file -> (output file, permalink, nav title, nav_order, description)
REFERENCES = [
    ("ECOCASH-EIP-API.md", "reference-documentation-tab.md", "/reference/documentation-tab/",
     "Documentation tab (verbatim)", 1,
     "The EcoCash developer portal's EIP Documentation tab reproduced verbatim: "
     "overview, API reference, error codes, test data, SMS and test script."),
    ("ECOCASH-EIP-SDK-REFERENCE.md", "reference-sdks-tab.md", "/reference/sdks-tab/",
     "SDKs & Codegen tab (verbatim)", 2,
     "All 15 EcoCash EIP SDK samples from the portal verbatim: Java, PHP/Laravel, "
     "JavaScript, C# and Python, with review notes on their defects."),
    ("ECOCASH-DEVELOPER-PORTAL-GETTING-STARTED.md", "reference-portal-getting-started.md",
     "/reference/portal-getting-started/", "Portal walkthrough", 3,
     "Screenshot walkthrough of the EcoCash Developer Portal: sign in, request sandbox "
     "access, inbox credentials, Authorization header and test number verification."),
]
REFERENCE_PARENT = ("reference.md", "/reference/", "Portal reference", 13,
                    "The EcoCash developer portal's own EIP documentation and SDK samples, "
                    "reproduced verbatim for reference alongside this guide.")

REPO_FILES = {"LICENSE", "NOTICE", "CHANGELOG.md"}


def read(path):
    return io.open(path, encoding="utf-8").read().replace("\r\n", "\n")


def q(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


def slug(heading):
    """GitHub heading slug - kramdown's GFM parser produces the same ids."""
    s = re.sub(r"<[^>]+>", "", heading).strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    return s.replace(" ", "-")


def rel(src_permalink, dst_permalink):
    """Relative URL between two directory-style permalinks."""
    r = posixpath.relpath(dst_permalink, src_permalink)
    return "./" if r == "." else r.rstrip("/") + "/"


def split_code(body):
    """Yield (is_code, text) chunks so transforms never touch fenced code."""
    parts = re.split(r"(^```.*?^```[ \t]*$)", body, flags=re.S | re.M)
    for i, p in enumerate(parts):
        yield (i % 2 == 1, p)


def readme_sections():
    text = read(README)
    heads = [(m.start(), int(m.group(1)), m.group(2))
             for m in re.finditer(r"^## (\d+)\. (.+)$", text, re.M)]
    # ignore any "## N." inside code fences
    fenced = [(m.start(), m.end()) for m in re.finditer(r"^```.*?^```", text, re.S | re.M)]
    heads = [h for h in heads if not any(a <= h[0] < b for a, b in fenced)]
    out = {}
    for i, (pos, num, title) in enumerate(heads):
        end = heads[i + 1][0] if i + 1 < len(heads) else len(text)
        chunk = text[pos:end].rstrip()
        chunk = re.sub(r"\n---\s*$", "", chunk).rstrip()
        out[num] = (title, chunk)
    return out


def anchor_map(sections):
    """README anchor -> (permalink, anchor or None)."""
    m = {}
    for num, (title, chunk) in sections.items():
        permalink = SECTIONS[num][1]
        m[slug("%d. %s" % (num, title))] = (permalink, None)
        body = re.sub(r"^```.*?^```", "", chunk, flags=re.S | re.M)
        for h in re.findall(r"^#{3,6}\s+(.+?)\s*$", body, re.M):
            m[slug(h)] = (permalink, slug(h))
    return m


def rewrite_links(text, self_permalink, anchors, ref_links):
    def link(target):
        if target.startswith(("http://", "https://", "mailto:", "tel:", "{{")):
            return target
        if target.startswith("#"):
            a = target[1:]
            if a in anchors:
                permalink, sub = anchors[a]
                if permalink == self_permalink:
                    return "#" + (sub or "")
                return rel(self_permalink, permalink) + ("#" + sub if sub else "")
            return target
        base, _, frag = target.partition("#")
        name = posixpath.basename(base)
        if base.startswith("reference/") or base.startswith("../reference/") or name in ref_links:
            if name in ref_links:
                return rel(self_permalink, ref_links[name]) + ("#" + frag if frag else "")
        if name in REPO_FILES:
            return "%s/blob/main/%s" % (REPO, name)
        if base.startswith("docs/assets/") or base.startswith("../docs/assets/"):
            return "{{ '%s' | relative_url }}" % base[base.index("/assets/"):]
        repo_path = base.lstrip("./").rstrip("/")
        if repo_path and os.path.exists(os.path.join(ROOT, repo_path)):
            kind = "tree" if os.path.isdir(os.path.join(ROOT, repo_path)) else "blob"
            return "%s/%s/main/%s" % (REPO, kind, repo_path) + ("#" + frag if frag else "")
        return target

    def md(m):
        return "](%s)" % link(m.group(1))

    def html(m):
        return '%s="%s"' % (m.group(1), link(m.group(2)))

    out = []
    for is_code, chunk in split_code(text):
        if not is_code:
            chunk = re.sub(r"\]\(([^)\s]+)\)", md, chunk)
            chunk = re.sub(r'\b(src|href)="([^"]+)"', html, chunk)
        out.append(chunk)
    return "".join(out)


def demote(chunk):
    """Drop the `## N. Title` line and move every deeper heading up one level."""
    chunk = re.sub(r"\A## .*\n+", "", chunk)
    out = []
    for is_code, part in split_code(chunk):
        if not is_code:
            part = re.sub(r"^#(#{2,6}) ", r"\1 ", part, flags=re.M)
        out.append(part)
    return "".join(out)


def front_matter(title, order, permalink, desc, image_slug, source, extra=()):
    fm = ["---", BANNER,
          "title: %s" % q(title),
          "nav_order: %d" % order,
          "permalink: %s" % permalink,
          "description: %s" % q(desc),
          "date: %s" % PUBLISHED,
          "last_modified_at: %s" % DATE_TOKEN,
          "seo:",
          "  type: WebPage",
          "image:",
          "  path: /assets/og/%s.png" % image_slug,
          "  width: 1200",
          "  height: 630",
          "  alt: %s" % q("EcoCash Instant Payment API - " + SITE_NAME if permalink == "/"
                          else "%s - %s" % (title, SITE_NAME)),
          "source_file: %s" % source]
    fm.extend(extra)
    fm.append("---")
    return "\n".join(fm) + "\n\n"


def footer(source, what):
    return ("\n\n---\n\n"
            "This page is generated from %s in "
            "[`%s`](%s/blob/main/%s). "
            "Spotted something wrong? [Open an issue](%s/issues).\n"
            % (what, source, REPO, source, REPO))


# The same hero as 67even's other documentation sites (paynow-integration-skill,
# paynow-billpay-skill): the 67even mark, one h1, the tagline, four badges and two
# buttons. The partner's logo - EcoCash's - lives in the sidebar footer
# (_includes/nav_footer_custom.html), exactly where those sites put Paynow's.
HERO = """<div class="hero" markdown="0">
  <img class="hero-mark" src="{{ '/assets/images/67even-logo.png' | relative_url }}" alt="67even">
  <h1 class="hero-title">EcoCash EIP Developer Guide</h1>
  <p class="hero-tagline">Integrate EcoCash Instant Payment step by step: charge a wallet, check the result, refund it and go live.</p>
  <p class="hero-badges">
    <a href="https://github.com/67even/ecocash-instant-payment-api/stargazers"><img src="https://img.shields.io/github/stars/67even/ecocash-instant-payment-api?style=flat-square&logo=github&label=Stars&color=FF3131&labelColor=0C0E0B" alt="GitHub stars"></a>
    <a href="https://github.com/67even/ecocash-instant-payment-api/actions/workflows/tests.yml"><img src="https://img.shields.io/github/actions/workflow/status/67even/ecocash-instant-payment-api/tests.yml?branch=main&style=flat-square&logo=githubactions&logoColor=white&label=tests&color=FF3131&labelColor=0C0E0B" alt="Tests"></a>
    <a href="https://github.com/67even/ecocash-instant-payment-api/blob/main/LICENSE"><img src="https://img.shields.io/github/license/67even/ecocash-instant-payment-api?style=flat-square&label=License&color=FF3131&labelColor=0C0E0B" alt="MIT licence"></a>
    <a href="https://github.com/67even/ecocash-instant-payment-api"><img src="https://img.shields.io/github/last-commit/67even/ecocash-instant-payment-api?style=flat-square&label=Updated&color=FF3131&labelColor=0C0E0B" alt="Last commit"></a>
  </p>
</div>

<div class="hero-actions" markdown="1">
[View on GitHub](https://github.com/67even/ecocash-instant-payment-api){: .btn .btn-primary }
[Install the skill](install/){: .btn }
</div>

"""


def home_contents():
    """The "Where to start" table, in the same form as the other 67even sites."""
    rows = ["## Where to start\n", "| | |", "|:--|:--|"]
    for num in sorted(SECTIONS, key=lambda n: SECTIONS[n][3]):
        if num == 1:
            continue
        _, permalink, title, _, desc = SECTIONS[num]
        rows.append("| [**%s**](%s) | %s |" % (title, permalink.lstrip("/"), BLURBS[num]))
    rows.append("| [**%s**](%s) | %s |" % (REFERENCE_PARENT[2], REFERENCE_PARENT[1].lstrip("/"),
                                           "The portal's own Documentation and SDK tabs, verbatim."))
    return "\n".join(rows) + "\n\n---\n\n## Overview\n"


BLURBS = {
    2: "Register, get sandbox credentials from the Inbox, verify a test number.",
    3: "The Basic auth header, and where to keep credentials.",
    4: "Charge, approve, look up and refund with cURL, start to finish.",
    5: "Every endpoint, field, response and HTTP status.",
    6: "Transaction statuses and error codes E001-E015, and which to retry.",
    7: "PIN test matrix, test numbers, merchant values and the test checklist.",
    8: "Tested clients for PHP/Laravel, Node.js, Python, Java and C#.",
    9: "Merchant validation, test evidence and the production request.",
    10: "Something is broken right now. Symptom-to-cause table.",
    11: "Where the portal contradicts itself, and what to do.",
    12: "Install the Claude skill and let Claude write and review your EcoCash integration.",
    13: "Repository layout, sources and licence.",
}


def build():
    sections = readme_sections()
    missing = set(SECTIONS) - set(sections)
    if missing:
        sys.exit("README.md is missing section(s): %s" % sorted(missing))
    anchors = anchor_map(sections)
    ref_links = {src: permalink for src, _, permalink, _, _, _ in REFERENCES}

    pages = {}
    for num, (fname, permalink, title, order, desc) in SECTIONS.items():
        _, chunk = sections[num]
        body = demote(chunk)
        body = rewrite_links(body, permalink, anchors, ref_links)
        image_slug = "home" if permalink == "/" else permalink.strip("/")
        if num == 1:
            text = HERO + home_contents() + "\n" + body.strip() + "\n"
        else:
            text = "# %s\n\n%s" % (title, body.strip()) + "\n"
        pages[fname] = (front_matter(title, order, permalink, desc, image_slug, "README.md")
                        + text + footer("README.md", "section %d of the README" % num))

    # the reference parent and its children
    fname, permalink, title, order, desc = REFERENCE_PARENT
    items = "\n".join("- [%s](%s)" % (t, rel(permalink, p)) + " - " + d
                      for _, _, p, t, _, d in REFERENCES)
    pages[fname] = (
        front_matter(title, order, permalink, desc, "reference", "reference/", ["has_children: true"])
        + "# %s\n\n" % title
        + "These pages reproduce the EcoCash Developer Portal's own material **as published**, "
          "including its inconsistencies. For the clear, corrected walkthrough, start with the "
          "[guide](../). Where the two differ, see [Known portal issues](../known-issues/).\n\n"
        + items + "\n" + footer("reference/", "the files"))

    for src, fname, permalink, title, order, desc in REFERENCES:
        body = read(os.path.join(ROOT, "reference", src))
        body = re.sub(r"\A#\s+.*?\n+", "", body, count=1)
        body = rewrite_links(body, permalink, {}, ref_links)
        pages[fname] = (
            front_matter(title, order, permalink, desc, permalink.strip("/").replace("/", "-"),
                         "reference/" + src, ["parent: %s" % q(REFERENCE_PARENT[2])])
            + "# %s\n\n" % title + body.rstrip() + "\n"
            + footer("reference/" + src, "the file"))
    return pages


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if docs/ does not match the sources")
    args = ap.parse_args()

    os.makedirs(DOCS, exist_ok=True)
    pages = build()
    today = datetime.date.today().isoformat()
    stale = []
    for name, template in sorted(pages.items()):
        path = os.path.join(DOCS, name)
        current = read(path) if os.path.exists(path) else None
        previous = ""
        if current:
            m = re.search(r"^last_modified_at:\s*(\S+)\s*$", current, re.M)
            previous = m.group(1) if m else ""
        content = template.replace(DATE_TOKEN, previous or today)
        if current == content:
            state = "unchanged"
        else:
            content = template.replace(DATE_TOKEN, today)
            state = "STALE" if args.check else "written"
            stale.append(name)
            if not args.check:
                io.open(path, "w", encoding="utf-8", newline="\n").write(content)
        print("  %-40s %s" % (name, state))

    # a page left behind by a removed section would keep publishing stale content
    generated = set(pages)
    orphans = [f for f in os.listdir(DOCS) if f.endswith(".md") and f not in generated]
    for f in orphans:
        print("  %-40s ORPHAN (not generated - delete it or add it to build_docs.py)" % f)

    if args.check and (stale or orphans):
        print("\ndocs/ is out of date with README.md / reference/: %s" % ", ".join(stale + orphans))
        print("Run: python3 tools/build_docs.py")
        return 1
    print("\n%d page(s), %d changed" % (len(pages), len(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
