#!/usr/bin/env python3
"""Generate the Claude skill's references, templates and config from README.md.

The skill in ecocash-skills/ecocash-instant-payment/ must know exactly what this
repository knows - no more, no less. So only SKILL.md and scripts/ are written by
hand; everything the skill reads on demand is GENERATED from the same sources as
the documentation site:

  references/<topic>.md      one per README section (2-11), headings kept, images
                             turned into text notes, cross-links pointed at the
                             other reference files
  references/portal-*.md     the portal's Documentation and SDKs & Codegen tabs,
                             verbatim, from reference/
  templates/<stack>/...      the tested code examples from README section 8,
                             extracted block by block
  config/eip.env.example     the .env block from README section 3.2

CI runs this with --check and fails if the skill has drifted from the README.

    python3 tools/build_skill.py          # regenerate
    python3 tools/build_skill.py --check  # exit 1 if the skill is stale
"""

import argparse
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README = os.path.join(ROOT, "README.md")
SKILL = os.path.join(ROOT, "ecocash-skills", "ecocash-instant-payment")
SITE = "https://67even.github.io/ecocash-instant-payment-api"

# README section number -> reference file name and a one-line purpose
REFERENCES = {
    2: ("portal-onboarding.md", "Getting sandbox access on the EcoCash Developer Portal, step by step."),
    3: ("authentication.md", "HTTP Basic auth, storing credentials and merchant values, auth errors."),
    4: ("first-payment.md", "A full charge -> approve -> lookup -> refund walkthrough with cURL."),
    5: ("api-reference.md", "Every endpoint, request field, response field and HTTP status."),
    6: ("statuses-and-errors.md", "Transaction statuses, error codes E001-E015, retry rules."),
    7: ("sandbox-testing.md", "PIN matrix, test numbers, merchant values, SMS, test checklist."),
    8: ("code-examples.md", "Language guidance and the pitfalls in the portal's SDK samples."),
    9: ("go-live.md", "Production access steps and the go-live checklist."),
    10: ("troubleshooting.md", "Symptom -> cause -> fix, debugging tips, support contacts."),
    11: ("known-issues.md", "Where the portal contradicts itself, and the open questions."),
}

VERBATIM = [
    ("reference/ECOCASH-EIP-API.md", "portal-documentation-tab.md",
     "The portal's Documentation tab, verbatim, with its own review notes."),
    ("reference/ECOCASH-EIP-SDK-REFERENCE.md", "portal-sdk-samples.md",
     "All 15 SDK samples from the portal's SDKs & Codegen tab, verbatim, with review notes."),
]

# Code blocks of README section 8 -> template files. Each block is found by a marker
# it must contain, not by position, so reordering the README cannot mis-file code.
TEMPLATES = [
    ("php", "'ecocash' => [", "templates/php-laravel/config-services-ecocash.php",
     "<?php\n\n// Add this entry to the array returned by config/services.php.\n\nreturn [\n    %s\n];\n"),
    ("php", "class EcoCash", "templates/php-laravel/EcoCash.php", None),
    ("javascript", "export function charge", "templates/node/ecocash.js", None),
    ("python", "def charge(", "templates/python/ecocash.py", None),
    ("yaml", "eip:", "templates/java/application.yml", None),
    ("java", "class EcoCashClient", "templates/java/EcoCashClient.java", None),
    ("csharp", "class EcoCashClient", "templates/dotnet/EcoCashClient.cs", None),
    ("dotenv", "EIP_BASE_URL=", "config/eip.env.example", None),
]

BANNER = ("<!-- GENERATED by tools/build_skill.py from %s - edit the source, "
          "then re-run it. -->\n\n")


def read(path):
    return io.open(path, encoding="utf-8").read().replace("\r\n", "\n")


def slug(heading):
    s = re.sub(r"<[^>]+>", "", heading).strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    return s.replace(" ", "-")


def split_code(body):
    parts = re.split(r"(^```.*?^```[ \t]*$)", body, flags=re.S | re.M)
    for i, p in enumerate(parts):
        yield (i % 2 == 1, p)


def sections():
    text = read(README)
    fenced = [(m.start(), m.end()) for m in re.finditer(r"^```.*?^```", text, re.S | re.M)]
    heads = [(m.start(), int(m.group(1)), m.group(2))
             for m in re.finditer(r"^## (\d+)\. (.+)$", text, re.M)
             if not any(a <= m.start() < b for a, b in fenced)]
    out = {}
    for i, (pos, num, title) in enumerate(heads):
        end = heads[i + 1][0] if i + 1 < len(heads) else len(text)
        out[num] = (title, re.sub(r"\n---\s*$", "", text[pos:end].rstrip()).rstrip())
    return out


def anchor_map(secs):
    """README anchor -> (reference file or None, sub-anchor or None)."""
    m = {}
    for num, (title, chunk) in secs.items():
        ref = REFERENCES.get(num, (None,))[0]
        m[slug("%d. %s" % (num, title))] = (ref, None)
        body = re.sub(r"^```.*?^```", "", chunk, flags=re.S | re.M)
        for h in re.findall(r"^#{3,6}\s+(.+?)\s*$", body, re.M):
            m[slug(h)] = (ref, slug(h))
    return m


def rewrite(text, self_ref, anchors):
    def link(target):
        if target.startswith(("http://", "https://", "mailto:", "tel:")):
            return target
        if target.startswith("#"):
            ref, sub = anchors.get(target[1:], (None, None))
            if ref is None:
                return SITE + "/"
            if ref == self_ref:
                return "#" + (sub or "")
            return ref + ("#" + sub if sub else "")
        base = target.split("#")[0]
        name = os.path.basename(base)
        for src, dst, _ in VERBATIM:
            if name == os.path.basename(src):
                return dst
        return "https://github.com/67even/ecocash-instant-payment-api/blob/main/" + base.lstrip("./")

    out = []
    for is_code, part in split_code(text):
        if not is_code:
            # Screenshots cannot travel inside a skill; keep what they show as text.
            part = re.sub(r"!\[([^\]]*)\]\([^)]+\)",
                          lambda m: "*(Screenshot on the portal: %s. See %s/getting-started/)*"
                          % (m.group(1), SITE), part)
            part = re.sub(r"\]\(([^)\s]+)\)", lambda m: "](%s)" % link(m.group(1)), part)
        out.append(part)
    return "".join(out)


def with_toc(doc):
    """Long reference files get a table of contents under their intro, so Claude can
    jump to the part it needs instead of reading hundreds of lines."""
    if doc.count("\n") <= 300 or re.search(r"^#{2,3} (Table of )?Contents", doc, re.M | re.I):
        return doc
    heads = []
    for is_code, part in split_code(doc):
        if not is_code:
            heads += re.findall(r"^(#{2,3}) (.+?)\s*$", part, re.M)
    if len(heads) < 3:
        return doc
    toc = ["**Contents** (search for the heading text to jump to it)\n"]
    for hashes, title in heads:
        toc.append("%s- %s" % ("  " * (len(hashes) - 2), re.sub(r"[`*]", "", title)))
    # after the banner, the title and the purpose line, i.e. before the first real body line
    m = re.match(r"<!--[^\n]*-->\n\n(?:# [^\n]*\n\n)?> [^\n]*\n\n", doc)
    at = m.end() if m else 0
    return doc[:at] + "\n".join(toc) + "\n\n" + doc[at:]


def build():
    secs = sections()
    anchors = anchor_map(secs)
    files = {}

    for num, (name, purpose) in REFERENCES.items():
        title, chunk = secs[num]
        body = re.sub(r"\A## .*\n+", "", chunk)
        demoted = []
        for is_code, part in split_code(body):
            if not is_code:
                part = re.sub(r"^#(#{2,6}) ", r"\1 ", part, flags=re.M)
            demoted.append(part)
        body = rewrite("".join(demoted), name, anchors)
        files["references/" + name] = (
            BANNER % ("README.md section %d" % num)
            + "# %s\n\n> %s\n\n" % (title, purpose) + body.strip() + "\n")

    for src, dst, purpose in VERBATIM:
        body = read(os.path.join(ROOT, src))
        body = re.sub(r"\]\((\.\./)?docs/assets/images/screens/([^)]+)\)",
                      r"](%s/assets/images/screens/\2)" % SITE, body)
        files["references/" + dst] = BANNER % src + "> %s\n\n" % purpose + body.rstrip() + "\n"

    code = secs[8][1] + "\n" + secs[3][1]
    blocks = re.findall(r"^```(\w+)\n(.*?)^```", code, re.S | re.M)
    for lang, marker, dst, wrap in TEMPLATES:
        hits = [c for l, c in blocks if l == lang and marker in c]
        if len(hits) != 1:
            sys.exit("expected exactly one %s block containing %r in README, found %d"
                     % (lang, marker, len(hits)))
        c = hits[0]
        if wrap:
            c = wrap % c.strip().replace("\n", "\n    ")
        files[dst] = c.rstrip() + "\n"

    for rel in list(files):
        if rel.startswith("references/"):
            files[rel] = with_toc(files[rel])
    return files


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the skill is stale")
    args = ap.parse_args()

    files = build()
    stale = []
    for rel, content in sorted(files.items()):
        path = os.path.join(SKILL, rel)
        current = read(path) if os.path.exists(path) else None
        if current == content:
            state = "unchanged"
        else:
            stale.append(rel)
            state = "STALE" if args.check else "written"
            if not args.check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                io.open(path, "w", encoding="utf-8", newline="\n").write(content)
        print("  %-48s %s" % (rel, state))

    # generated folders must hold nothing but generated files
    orphans = []
    for folder in ("references", "templates", "config"):
        for dp, _, fn in os.walk(os.path.join(SKILL, folder)):
            for f in fn:
                rel = os.path.relpath(os.path.join(dp, f), SKILL).replace(os.sep, "/")
                if rel not in files:
                    orphans.append(rel)
                    print("  %-48s ORPHAN (not generated)" % rel)

    if args.check and (stale or orphans):
        print("\nthe skill is out of date with README.md: %s" % ", ".join(stale + orphans))
        print("Run: python3 tools/build_skill.py")
        return 1
    print("\n%d generated file(s), %d changed" % (len(files), len(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
